drop table VIDEO;

CREATE TABLE VIDEO ( VIDEO_NAME VARCHAR2(50),
  VIDEO_SRC VARCHAR2(50) NOT NULL,
  VIDEO_LENGTH VARCHAR2(50));

--За 1
INSERT INTO VIDEO (VIDEO_NAME, VIDEO_SRC, VIDEO_LENGTH) VALUES ('forest','oSmUI3m2kLk','03:08:22');
--За 2
INSERT INTO VIDEO (VIDEO_NAME, VIDEO_SRC, VIDEO_LENGTH) VALUES ('piano concerto','l0IoPQM1HlU','00:14:16');
--За 3
INSERT INTO VIDEO (VIDEO_NAME, VIDEO_SRC, VIDEO_LENGTH) VALUES ('game','knV-5VciTTQ','00:08:21');

COMMIT;

SELECT * FROM VIDEO;